<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.hid4java</groupId>
  <artifactId>hid4java</artifactId>
  <version>develop-SNAPSHOT</version>

  <name>hid4java</name>
  <description>A cross-platform Java Native Access (JNA) wrapper for the libusb/hidapi library</description>

  <url>https://github.com/gary-rowe/hid4java</url>
  <inceptionYear>2014</inceptionYear>

  <developers>
    <developer>
      <name>Gary Rowe</name>
      <email>g.rowe@froot.co.uk</email>
    </developer>
  </developers>

  <licenses>
    <license>
      <name>MIT</name>
      <url>https://www.opensource.org/licenses/mit-license.php</url>
      <distribution>repo</distribution>
      <comments>All source code is under the MIT license.</comments>
    </license>
  </licenses>

  <issueManagement>
    <system>GitHub</system>
    <url>https://github.com/gary-rowe/hid4java/issues</url>
  </issueManagement>

  <distributionManagement>
    <snapshotRepository>
      <id>sonatype-nexus-snapshots</id>
      <name>Sonatype Nexus Snapshots</name>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </snapshotRepository>
    <repository>
      <id>sonatype-nexus-staging</id>
      <name>Nexus Release Repository</name>
      <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
    </repository>
    <downloadUrl>https://oss.sonatype.org/content/groups/public/org/hid4java</downloadUrl>
  </distributionManagement>

  <scm>
    <connection>scm:git:git@github.com:gary-rowe/hid4java.git</connection>
    <developerConnection>scm:git:git@github.com:gary-rowe/hid4java.git</developerConnection>
    <url>git@github.com:gary-rowe/hid4java.git</url>
    <tag>HEAD</tag>
  </scm>

  <properties>
    <!-- Ensure source is under UTF-8 -->
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <!-- Support basic language features only -->
    <maven.compiler.source>1.8</maven.compiler.source>
    <!-- Target the oldest long term support at time of compilation -->
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>

  <profiles>

    <!-- Only activated during release -->
    <profile>
      <id>release-sign-artifacts</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-gpg-plugin</artifactId>
            <version>3.2.3</version>
            <executions>
              <execution>
                <id>sign-artifacts</id>
                <phase>verify</phase>
                <goals>
                  <goal>sign</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>

  </profiles>

  <build>
    <plugins>

      <!-- Handle unit test execution -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.1.2</version>
      </plugin>

      <!-- Generates a source code JAR during package -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <version>3.3.0</version>
        <executions>
          <execution>
            <id>attach-sources</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <!-- Javadocs -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>3.6.3</version>
        <configuration>
          <source>8</source>
        </configuration>
        <executions>
          <execution>
            <id>attach-javadocs</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <!-- For deploying to Maven Central -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-release-plugin</artifactId>
        <version>3.0.1</version>
        <configuration>
          <autoVersionSubmodules>true</autoVersionSubmodules>
          <mavenExecutorId>forked-path</mavenExecutorId>
          <releaseProfiles>release-sign-artifacts</releaseProfiles>
        </configuration>
      </plugin>

      <!-- Generates a META/MANIFEST.MF file to assist programmatic library version (see #69)-->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.3.0</version>
        <configuration>
          <archive>
            <manifest>
              <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
            </manifest>
          </archive>
        </configuration>
      </plugin>

    </plugins>
  </build>

  <dependencies>
    <!-- Java Native Access (JNA) -->
    <dependency>
      <groupId>net.java.dev.jna</groupId>
      <artifactId>jna</artifactId>
      <!-- 5.7.0 JNA supports darwin-aarch64 -->
      <!-- 5.8.0 JNA supports linux-riscv64 -->
      <!-- Latest version generally recommended -->
      <version>[5.8.0,)</version>
    </dependency>

    <!-- JetBrains annotations -->
    <dependency>
      <groupId>org.jetbrains</groupId>
      <artifactId>annotations</artifactId>
      <version>26.0.2</version>
    </dependency>

    <!-- JUnit -->
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>5.10.2</version>
      <scope>test</scope>
    </dependency>

  </dependencies>

</project>
